// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cards/events.proto

package cards

import (
	common "github.com/BakhodiribnYashinibnMansur/XBank/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CardIssued - published when a new card is created
type CardIssued struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CardId        string                 `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardType      string                 `protobuf:"bytes,5,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	MaskedPan     string                 `protobuf:"bytes,6,opt,name=masked_pan,json=maskedPan,proto3" json:"masked_pan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardIssued) Reset() {
	*x = CardIssued{}
	mi := &file_cards_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardIssued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardIssued) ProtoMessage() {}

func (x *CardIssued) ProtoReflect() protoreflect.Message {
	mi := &file_cards_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardIssued.ProtoReflect.Descriptor instead.
func (*CardIssued) Descriptor() ([]byte, []int) {
	return file_cards_events_proto_rawDescGZIP(), []int{0}
}

func (x *CardIssued) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CardIssued) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardIssued) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CardIssued) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CardIssued) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CardIssued) GetMaskedPan() string {
	if x != nil {
		return x.MaskedPan
	}
	return ""
}

// CardBlocked - published when a card is blocked
type CardBlocked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CardId        string                 `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardBlocked) Reset() {
	*x = CardBlocked{}
	mi := &file_cards_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardBlocked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardBlocked) ProtoMessage() {}

func (x *CardBlocked) ProtoReflect() protoreflect.Message {
	mi := &file_cards_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardBlocked.ProtoReflect.Descriptor instead.
func (*CardBlocked) Descriptor() ([]byte, []int) {
	return file_cards_events_proto_rawDescGZIP(), []int{1}
}

func (x *CardBlocked) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CardBlocked) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardBlocked) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CardBlocked) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CardActivated - published when a card is activated
type CardActivated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CardId        string                 `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardActivated) Reset() {
	*x = CardActivated{}
	mi := &file_cards_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardActivated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardActivated) ProtoMessage() {}

func (x *CardActivated) ProtoReflect() protoreflect.Message {
	mi := &file_cards_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardActivated.ProtoReflect.Descriptor instead.
func (*CardActivated) Descriptor() ([]byte, []int) {
	return file_cards_events_proto_rawDescGZIP(), []int{2}
}

func (x *CardActivated) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CardActivated) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardActivated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_cards_events_proto protoreflect.FileDescriptor

const file_cards_events_proto_rawDesc = "" +
	"\n" +
	"\x12cards/events.proto\x12\vxbank.cards\x1a\x15common/metadata.proto\"\xcd\x01\n" +
	"\n" +
	"CardIssued\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcard_type\x18\x05 \x01(\tR\bcardType\x12\x1d\n" +
	"\n" +
	"masked_pan\x18\x06 \x01(\tR\tmaskedPan\"\x8b\x01\n" +
	"\vCardBlocked\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"u\n" +
	"\rCardActivated\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userIdB9Z7github.com/BakhodiribnYashinibnMansur/XBank/proto/cardsb\x06proto3"

var (
	file_cards_events_proto_rawDescOnce sync.Once
	file_cards_events_proto_rawDescData []byte
)

func file_cards_events_proto_rawDescGZIP() []byte {
	file_cards_events_proto_rawDescOnce.Do(func() {
		file_cards_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cards_events_proto_rawDesc), len(file_cards_events_proto_rawDesc)))
	})
	return file_cards_events_proto_rawDescData
}

var file_cards_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cards_events_proto_goTypes = []any{
	(*CardIssued)(nil),      // 0: xbank.cards.CardIssued
	(*CardBlocked)(nil),     // 1: xbank.cards.CardBlocked
	(*CardActivated)(nil),   // 2: xbank.cards.CardActivated
	(*common.Metadata)(nil), // 3: xbank.common.Metadata
}
var file_cards_events_proto_depIdxs = []int32{
	3, // 0: xbank.cards.CardIssued.metadata:type_name -> xbank.common.Metadata
	3, // 1: xbank.cards.CardBlocked.metadata:type_name -> xbank.common.Metadata
	3, // 2: xbank.cards.CardActivated.metadata:type_name -> xbank.common.Metadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cards_events_proto_init() }
func file_cards_events_proto_init() {
	if File_cards_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cards_events_proto_rawDesc), len(file_cards_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cards_events_proto_goTypes,
		DependencyIndexes: file_cards_events_proto_depIdxs,
		MessageInfos:      file_cards_events_proto_msgTypes,
	}.Build()
	File_cards_events_proto = out.File
	file_cards_events_proto_goTypes = nil
	file_cards_events_proto_depIdxs = nil
}
