// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: accounts/events.proto

package accounts

import (
	common "github.com/BakhodiribnYashinibnMansur/XBank/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccountOpened - published when a new account is created
type AccountOpened struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountNumber string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountOpened) Reset() {
	*x = AccountOpened{}
	mi := &file_accounts_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountOpened) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountOpened) ProtoMessage() {}

func (x *AccountOpened) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountOpened.ProtoReflect.Descriptor instead.
func (*AccountOpened) Descriptor() ([]byte, []int) {
	return file_accounts_events_proto_rawDescGZIP(), []int{0}
}

func (x *AccountOpened) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AccountOpened) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountOpened) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountOpened) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *AccountOpened) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// AccountCredited - published when funds are deposited
type AccountCredited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Balance       int64                  `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountCredited) Reset() {
	*x = AccountCredited{}
	mi := &file_accounts_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountCredited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCredited) ProtoMessage() {}

func (x *AccountCredited) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCredited.ProtoReflect.Descriptor instead.
func (*AccountCredited) Descriptor() ([]byte, []int) {
	return file_accounts_events_proto_rawDescGZIP(), []int{1}
}

func (x *AccountCredited) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AccountCredited) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountCredited) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AccountCredited) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountCredited) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

// AccountDebited - published when funds are withdrawn
type AccountDebited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Balance       int64                  `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountDebited) Reset() {
	*x = AccountDebited{}
	mi := &file_accounts_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountDebited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDebited) ProtoMessage() {}

func (x *AccountDebited) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDebited.ProtoReflect.Descriptor instead.
func (*AccountDebited) Descriptor() ([]byte, []int) {
	return file_accounts_events_proto_rawDescGZIP(), []int{2}
}

func (x *AccountDebited) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AccountDebited) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountDebited) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AccountDebited) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountDebited) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

// AccountFrozen - published when account is frozen
type AccountFrozen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountFrozen) Reset() {
	*x = AccountFrozen{}
	mi := &file_accounts_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountFrozen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountFrozen) ProtoMessage() {}

func (x *AccountFrozen) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountFrozen.ProtoReflect.Descriptor instead.
func (*AccountFrozen) Descriptor() ([]byte, []int) {
	return file_accounts_events_proto_rawDescGZIP(), []int{3}
}

func (x *AccountFrozen) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AccountFrozen) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// AccountClosed - published when account is closed
type AccountClosed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountClosed) Reset() {
	*x = AccountClosed{}
	mi := &file_accounts_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountClosed) ProtoMessage() {}

func (x *AccountClosed) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountClosed.ProtoReflect.Descriptor instead.
func (*AccountClosed) Descriptor() ([]byte, []int) {
	return file_accounts_events_proto_rawDescGZIP(), []int{4}
}

func (x *AccountClosed) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AccountClosed) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

var File_accounts_events_proto protoreflect.FileDescriptor

const file_accounts_events_proto_rawDesc = "" +
	"\n" +
	"\x15accounts/events.proto\x12\x0exbank.accounts\x1a\x15common/metadata.proto\"\xbe\x01\n" +
	"\rAccountOpened\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12%\n" +
	"\x0eaccount_number\x18\x04 \x01(\tR\raccountNumber\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"\xb2\x01\n" +
	"\x0fAccountCredited\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x03R\abalance\"\xb1\x01\n" +
	"\x0eAccountDebited\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x03R\abalance\"b\n" +
	"\rAccountFrozen\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"b\n" +
	"\rAccountClosed\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountIdB<Z:github.com/BakhodiribnYashinibnMansur/XBank/proto/accountsb\x06proto3"

var (
	file_accounts_events_proto_rawDescOnce sync.Once
	file_accounts_events_proto_rawDescData []byte
)

func file_accounts_events_proto_rawDescGZIP() []byte {
	file_accounts_events_proto_rawDescOnce.Do(func() {
		file_accounts_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_events_proto_rawDesc), len(file_accounts_events_proto_rawDesc)))
	})
	return file_accounts_events_proto_rawDescData
}

var file_accounts_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_accounts_events_proto_goTypes = []any{
	(*AccountOpened)(nil),   // 0: xbank.accounts.AccountOpened
	(*AccountCredited)(nil), // 1: xbank.accounts.AccountCredited
	(*AccountDebited)(nil),  // 2: xbank.accounts.AccountDebited
	(*AccountFrozen)(nil),   // 3: xbank.accounts.AccountFrozen
	(*AccountClosed)(nil),   // 4: xbank.accounts.AccountClosed
	(*common.Metadata)(nil), // 5: xbank.common.Metadata
}
var file_accounts_events_proto_depIdxs = []int32{
	5, // 0: xbank.accounts.AccountOpened.metadata:type_name -> xbank.common.Metadata
	5, // 1: xbank.accounts.AccountCredited.metadata:type_name -> xbank.common.Metadata
	5, // 2: xbank.accounts.AccountDebited.metadata:type_name -> xbank.common.Metadata
	5, // 3: xbank.accounts.AccountFrozen.metadata:type_name -> xbank.common.Metadata
	5, // 4: xbank.accounts.AccountClosed.metadata:type_name -> xbank.common.Metadata
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_accounts_events_proto_init() }
func file_accounts_events_proto_init() {
	if File_accounts_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_events_proto_rawDesc), len(file_accounts_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accounts_events_proto_goTypes,
		DependencyIndexes: file_accounts_events_proto_depIdxs,
		MessageInfos:      file_accounts_events_proto_msgTypes,
	}.Build()
	File_accounts_events_proto = out.File
	file_accounts_events_proto_goTypes = nil
	file_accounts_events_proto_depIdxs = nil
}
