// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: notifications/events.proto

package notifications

import (
	common "github.com/BakhodiribnYashinibnMansur/XBank/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotificationRequested - published when a notification should be sent
type NotificationRequested struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type           string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Title          string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Body           string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Channel        string                 `protobuf:"bytes,7,opt,name=channel,proto3" json:"channel,omitempty"`
	Data           map[string]string      `protobuf:"bytes,8,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationRequested) Reset() {
	*x = NotificationRequested{}
	mi := &file_notifications_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequested) ProtoMessage() {}

func (x *NotificationRequested) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequested.ProtoReflect.Descriptor instead.
func (*NotificationRequested) Descriptor() ([]byte, []int) {
	return file_notifications_events_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationRequested) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NotificationRequested) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationRequested) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationRequested) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationRequested) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationRequested) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotificationRequested) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *NotificationRequested) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_notifications_events_proto protoreflect.FileDescriptor

const file_notifications_events_proto_rawDesc = "" +
	"\n" +
	"\x1anotifications/events.proto\x12\x13xbank.notifications\x1a\x15common/metadata.proto\"\xe8\x02\n" +
	"\x15NotificationRequested\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12\x18\n" +
	"\achannel\x18\a \x01(\tR\achannel\x12H\n" +
	"\x04data\x18\b \x03(\v24.xbank.notifications.NotificationRequested.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BAZ?github.com/BakhodiribnYashinibnMansur/XBank/proto/notificationsb\x06proto3"

var (
	file_notifications_events_proto_rawDescOnce sync.Once
	file_notifications_events_proto_rawDescData []byte
)

func file_notifications_events_proto_rawDescGZIP() []byte {
	file_notifications_events_proto_rawDescOnce.Do(func() {
		file_notifications_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_events_proto_rawDesc), len(file_notifications_events_proto_rawDesc)))
	})
	return file_notifications_events_proto_rawDescData
}

var file_notifications_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notifications_events_proto_goTypes = []any{
	(*NotificationRequested)(nil), // 0: xbank.notifications.NotificationRequested
	nil,                           // 1: xbank.notifications.NotificationRequested.DataEntry
	(*common.Metadata)(nil),       // 2: xbank.common.Metadata
}
var file_notifications_events_proto_depIdxs = []int32{
	2, // 0: xbank.notifications.NotificationRequested.metadata:type_name -> xbank.common.Metadata
	1, // 1: xbank.notifications.NotificationRequested.data:type_name -> xbank.notifications.NotificationRequested.DataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_notifications_events_proto_init() }
func file_notifications_events_proto_init() {
	if File_notifications_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_events_proto_rawDesc), len(file_notifications_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notifications_events_proto_goTypes,
		DependencyIndexes: file_notifications_events_proto_depIdxs,
		MessageInfos:      file_notifications_events_proto_msgTypes,
	}.Build()
	File_notifications_events_proto = out.File
	file_notifications_events_proto_goTypes = nil
	file_notifications_events_proto_depIdxs = nil
}
