// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: kyc/events.proto

package kyc

import (
	common "github.com/BakhodiribnYashinibnMansur/XBank/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KYCSubmitted - published when a KYC verification is submitted
type KYCSubmitted struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	VerificationId string                 `protobuf:"bytes,2,opt,name=verification_id,json=verificationId,proto3" json:"verification_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocumentType   string                 `protobuf:"bytes,4,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KYCSubmitted) Reset() {
	*x = KYCSubmitted{}
	mi := &file_kyc_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KYCSubmitted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KYCSubmitted) ProtoMessage() {}

func (x *KYCSubmitted) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KYCSubmitted.ProtoReflect.Descriptor instead.
func (*KYCSubmitted) Descriptor() ([]byte, []int) {
	return file_kyc_events_proto_rawDescGZIP(), []int{0}
}

func (x *KYCSubmitted) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *KYCSubmitted) GetVerificationId() string {
	if x != nil {
		return x.VerificationId
	}
	return ""
}

func (x *KYCSubmitted) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KYCSubmitted) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

// KYCApproved - published when a KYC verification is approved
type KYCApproved struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	VerificationId string                 `protobuf:"bytes,2,opt,name=verification_id,json=verificationId,proto3" json:"verification_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Level          string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KYCApproved) Reset() {
	*x = KYCApproved{}
	mi := &file_kyc_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KYCApproved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KYCApproved) ProtoMessage() {}

func (x *KYCApproved) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KYCApproved.ProtoReflect.Descriptor instead.
func (*KYCApproved) Descriptor() ([]byte, []int) {
	return file_kyc_events_proto_rawDescGZIP(), []int{1}
}

func (x *KYCApproved) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *KYCApproved) GetVerificationId() string {
	if x != nil {
		return x.VerificationId
	}
	return ""
}

func (x *KYCApproved) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KYCApproved) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

// KYCRejected - published when a KYC verification is rejected
type KYCRejected struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	VerificationId string                 `protobuf:"bytes,2,opt,name=verification_id,json=verificationId,proto3" json:"verification_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KYCRejected) Reset() {
	*x = KYCRejected{}
	mi := &file_kyc_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KYCRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KYCRejected) ProtoMessage() {}

func (x *KYCRejected) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KYCRejected.ProtoReflect.Descriptor instead.
func (*KYCRejected) Descriptor() ([]byte, []int) {
	return file_kyc_events_proto_rawDescGZIP(), []int{2}
}

func (x *KYCRejected) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *KYCRejected) GetVerificationId() string {
	if x != nil {
		return x.VerificationId
	}
	return ""
}

func (x *KYCRejected) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KYCRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_kyc_events_proto protoreflect.FileDescriptor

const file_kyc_events_proto_rawDesc = "" +
	"\n" +
	"\x10kyc/events.proto\x12\txbank.kyc\x1a\x15common/metadata.proto\"\xa9\x01\n" +
	"\fKYCSubmitted\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12'\n" +
	"\x0fverification_id\x18\x02 \x01(\tR\x0everificationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12#\n" +
	"\rdocument_type\x18\x04 \x01(\tR\fdocumentType\"\x99\x01\n" +
	"\vKYCApproved\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12'\n" +
	"\x0fverification_id\x18\x02 \x01(\tR\x0everificationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\"\x9b\x01\n" +
	"\vKYCRejected\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12'\n" +
	"\x0fverification_id\x18\x02 \x01(\tR\x0everificationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reasonB7Z5github.com/BakhodiribnYashinibnMansur/XBank/proto/kycb\x06proto3"

var (
	file_kyc_events_proto_rawDescOnce sync.Once
	file_kyc_events_proto_rawDescData []byte
)

func file_kyc_events_proto_rawDescGZIP() []byte {
	file_kyc_events_proto_rawDescOnce.Do(func() {
		file_kyc_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kyc_events_proto_rawDesc), len(file_kyc_events_proto_rawDesc)))
	})
	return file_kyc_events_proto_rawDescData
}

var file_kyc_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kyc_events_proto_goTypes = []any{
	(*KYCSubmitted)(nil),    // 0: xbank.kyc.KYCSubmitted
	(*KYCApproved)(nil),     // 1: xbank.kyc.KYCApproved
	(*KYCRejected)(nil),     // 2: xbank.kyc.KYCRejected
	(*common.Metadata)(nil), // 3: xbank.common.Metadata
}
var file_kyc_events_proto_depIdxs = []int32{
	3, // 0: xbank.kyc.KYCSubmitted.metadata:type_name -> xbank.common.Metadata
	3, // 1: xbank.kyc.KYCApproved.metadata:type_name -> xbank.common.Metadata
	3, // 2: xbank.kyc.KYCRejected.metadata:type_name -> xbank.common.Metadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kyc_events_proto_init() }
func file_kyc_events_proto_init() {
	if File_kyc_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kyc_events_proto_rawDesc), len(file_kyc_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kyc_events_proto_goTypes,
		DependencyIndexes: file_kyc_events_proto_depIdxs,
		MessageInfos:      file_kyc_events_proto_msgTypes,
	}.Build()
	File_kyc_events_proto = out.File
	file_kyc_events_proto_goTypes = nil
	file_kyc_events_proto_depIdxs = nil
}
