// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transfers/events.proto

package transfers

import (
	common "github.com/BakhodiribnYashinibnMansur/XBank/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransferCreated - published when a new transfer is initiated
type TransferCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TransferId    string                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	FromAccountId string                 `protobuf:"bytes,3,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   string                 `protobuf:"bytes,4,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferCreated) Reset() {
	*x = TransferCreated{}
	mi := &file_transfers_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferCreated) ProtoMessage() {}

func (x *TransferCreated) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferCreated.ProtoReflect.Descriptor instead.
func (*TransferCreated) Descriptor() ([]byte, []int) {
	return file_transfers_events_proto_rawDescGZIP(), []int{0}
}

func (x *TransferCreated) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TransferCreated) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferCreated) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *TransferCreated) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *TransferCreated) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferCreated) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransferCreated) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// TransferCompleted - published when transfer succeeds
type TransferCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TransferId    string                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	FromAccountId string                 `protobuf:"bytes,3,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   string                 `protobuf:"bytes,4,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferCompleted) Reset() {
	*x = TransferCompleted{}
	mi := &file_transfers_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferCompleted) ProtoMessage() {}

func (x *TransferCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferCompleted.ProtoReflect.Descriptor instead.
func (*TransferCompleted) Descriptor() ([]byte, []int) {
	return file_transfers_events_proto_rawDescGZIP(), []int{1}
}

func (x *TransferCompleted) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TransferCompleted) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferCompleted) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *TransferCompleted) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *TransferCompleted) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferCompleted) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// TransferFailed - published when transfer fails
type TransferFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.Metadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TransferId    string                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	FromAccountId string                 `protobuf:"bytes,3,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   string                 `protobuf:"bytes,4,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferFailed) Reset() {
	*x = TransferFailed{}
	mi := &file_transfers_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFailed) ProtoMessage() {}

func (x *TransferFailed) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFailed.ProtoReflect.Descriptor instead.
func (*TransferFailed) Descriptor() ([]byte, []int) {
	return file_transfers_events_proto_rawDescGZIP(), []int{2}
}

func (x *TransferFailed) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TransferFailed) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferFailed) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *TransferFailed) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *TransferFailed) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferFailed) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransferFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_transfers_events_proto protoreflect.FileDescriptor

const file_transfers_events_proto_rawDesc = "" +
	"\n" +
	"\x16transfers/events.proto\x12\x0fxbank.transfers\x1a\x15common/metadata.proto\"\x88\x02\n" +
	"\x0fTransferCreated\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\tR\n" +
	"transferId\x12&\n" +
	"\x0ffrom_account_id\x18\x03 \x01(\tR\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x04 \x01(\tR\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"\xe8\x01\n" +
	"\x11TransferCompleted\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\tR\n" +
	"transferId\x12&\n" +
	"\x0ffrom_account_id\x18\x03 \x01(\tR\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x04 \x01(\tR\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\"\xfd\x01\n" +
	"\x0eTransferFailed\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.xbank.common.MetadataR\bmetadata\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\tR\n" +
	"transferId\x12&\n" +
	"\x0ffrom_account_id\x18\x03 \x01(\tR\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x04 \x01(\tR\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reasonB=Z;github.com/BakhodiribnYashinibnMansur/XBank/proto/transfersb\x06proto3"

var (
	file_transfers_events_proto_rawDescOnce sync.Once
	file_transfers_events_proto_rawDescData []byte
)

func file_transfers_events_proto_rawDescGZIP() []byte {
	file_transfers_events_proto_rawDescOnce.Do(func() {
		file_transfers_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transfers_events_proto_rawDesc), len(file_transfers_events_proto_rawDesc)))
	})
	return file_transfers_events_proto_rawDescData
}

var file_transfers_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_transfers_events_proto_goTypes = []any{
	(*TransferCreated)(nil),   // 0: xbank.transfers.TransferCreated
	(*TransferCompleted)(nil), // 1: xbank.transfers.TransferCompleted
	(*TransferFailed)(nil),    // 2: xbank.transfers.TransferFailed
	(*common.Metadata)(nil),   // 3: xbank.common.Metadata
}
var file_transfers_events_proto_depIdxs = []int32{
	3, // 0: xbank.transfers.TransferCreated.metadata:type_name -> xbank.common.Metadata
	3, // 1: xbank.transfers.TransferCompleted.metadata:type_name -> xbank.common.Metadata
	3, // 2: xbank.transfers.TransferFailed.metadata:type_name -> xbank.common.Metadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_transfers_events_proto_init() }
func file_transfers_events_proto_init() {
	if File_transfers_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transfers_events_proto_rawDesc), len(file_transfers_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transfers_events_proto_goTypes,
		DependencyIndexes: file_transfers_events_proto_depIdxs,
		MessageInfos:      file_transfers_events_proto_msgTypes,
	}.Build()
	File_transfers_events_proto = out.File
	file_transfers_events_proto_goTypes = nil
	file_transfers_events_proto_depIdxs = nil
}
